/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TestPack;

public class AppTest {

      public static void main(String args[]){

          System.out.println("Hello Universe. Welcome to Gradle");
      }
}
